# Site settings
title:       Horntell | Help
email:       hello@horntell.com
author:      Mohit Mamoria
description: "Interactive Push Notifications for your website"
baseurl:     "/help"
url:         "http://docs.horntell.com"
destination: ./dist

# For Index Page
index:
    - category: 'Getting Started'
      articles:
      - 'Terminology': 'terminology'
      - 'How to integrate the JS widget (aka Horntell Center)': 'how-to-integrate-horntell-center'
      - 'What are various formats of notifications?': 'what-are-various-formats-of-notifications'
      - 'How can I test things out before pushing it in production? (tell about different environments)': 'how-can-i-test-things-out-before-pushing-it-in-production'
      - 'How to calculate the required hash of uid?': 'how-to-calculate-the-required-hash-of-uid'
      - 'How to send a notification?': 'how-to-send-a-notification'
      - 'How to send a notification using API?': 'how-to-send-a-notification-using-api'
      - 'How to setup proper campaigns?': 'how-to-setup-proper-campaigns'
      - 'How to use variables in your notifications?': 'how-to-use-variables-in-your-notifications'
    - category: 'FAQs'
      articles:
       - What does an app mean?: 'what-does-an-app-mean'
       - What does a profile mean?: 'what-does-a-profile-mean'
       - What does a horn mean?: 'what-does-a-horn-mean'
       - What does a campaign mean?: 'what-does-a-campaign-mean'
       - What does a segment mean?: 'what-does-a-segment-mean'
       - What additional data can I save in profiles?: 'what-additional-data-can-i-save-in-profiles'
       - When do I create a profile for an user?: 'when-do-i-create-a-profile-for-an-user'
       - Where do I find the secret keys of my app?: 'where-do-i-find-the-secret-keys-of-my-app'


# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     rdiscount
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
